### ISSUE TITLE
Slack welcome message

### ISSUE THREAD

**Issue by benfoxall** [remotehack/remotehack.github.io#118]
We can set a message for people when they first join the slack - might be a good place to give people more info.

Maybe something like:

> 🎉 Welcome to the Remote Hack Space 🎉 
>  We're usually on #general, drop in say hi anytime!  If we're on a hack day, look for the zoom link and we'll usually be hanging around on that.  

@lpmi-13 does that sound okay?  Anything else I should add?

---

![image](https://user-images.githubusercontent.com/51385/114303813-e836b180-9ac7-11eb-817e-379b4631aac8.png)

**Comment by lpmi-13** [comment]
Yep, looks good!

**Comment by benfoxall** [comment]
Ace! Updated :shipit:
