### ISSUE TITLE
Generate calendar output

### ISSUE THREAD

**Issue by benfoxall** [remotehack/remotehack.github.io#119]

**Comment by omgmog** [comment]
This is the format you would need to generate:

```
BEGIN:VCALENDAR

BEGIN:VEVENT
CREATED:20151219T021727Z
DTEND;TZID=America/Toronto:20170515T110000
DTSTAMP:20151219T021727Z
DTSTART;TZID=America/Toronto:20170515T100000
LAST-MODIFIED:20151219T021727Z
RRULE:FREQ=DAILY;UNTIL=20170519T035959Z
SEQUENCE:0
SUMMARY:Meeting
TRANSP:OPAQUE
UID:21B97459-D97B-4B23-AF2A-E2759745C299
END:VEVENT

END:VCALENDAR
```

With each event being the `BEGIN:VEVENT` to `END:VEVENT` block, and I'm sure there's some other metadata in the main `VALENDAR` block

**Comment by lpmi-13** [comment]
While we're here, can we add a "this is happening now" when the date/time is the same as the "next event"?

**Comment by omgmog** [comment]
> While we're here, can we add a "this is happening now" when the date/time is the same as the "next event"?

I think that would be down to your Calendar app, rather than the ICS feed

**Comment by lpmi-13** [comment]
Ah yes, I have misread the issue...was referring to the website

**Comment by omgmog** [comment]
👉 😎 👉 #120
