### ISSUE TITLE
🃏Planning Poker web app

### ISSUE THREAD

**Issue by benfoxall** [remotehack/remotehack.github.io#3]
Since our office has gone remote, one of the things that has become awkward is playing [planning poker](https://en.wikipedia.org/wiki/Planning_poker).  We've got a solution with zoom & a phone app, though it's a bit awkward.

I'm imagining something completely url based:

To "host" a session:
http://mega.hacks/poker/session-name

To be a "player":
http://mega.hacks/poker/session-name/ben

Tech-wise - I'm thinking of building [websocket service with api gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api.html) with a static frontend.

(I know these tools [exist](https://scrumpoker.online/) – though I think it'd be a fun project to make my own!)

**Comment by lpmi-13** [comment]
Tsk tsk with those unencrypted http prorocols...

**Comment by benfoxall** [comment]
Github repo!
http://github.com/benfoxall/poker

**Comment by benfoxall** [comment]
Even Newer repo:

➡️ https://github.com/remotehack/poker

**Comment by benfoxall** [comment]
This was fun! 🎴
