### ISSUE TITLE
Get the site to autoupdate with the next hackdate

### ISSUE THREAD

**Issue by lpmi-13** [remotehack/remotehack.github.io#43]
Even if we have to just hardcode an array, would be nice if the next hack date just rolled over after the event on the last saturday of the month.

Currently somebody needs to manually change the "next hack day is on X", which isnt super great.

**Comment by omgmog** [comment]
This was fixed in ab40130f8ae36a65c4547426032c8ea227f9e1ce :boom:

**Comment by lpmi-13** [comment]
noice
