### ISSUE TITLE
👩‍🎤Remote presence / avatar

### ISSUE THREAD

**Issue by spikeheap** [remotehack/remotehack.github.io#7]
I love the idea of being able to see who's around, but most of us don't set "away" diligently, and might just nip off to open the door for a someone. 

I'm wondering if it's possible to take the webcam feed and magic that into a cartoon avatar of the person. This might get rid of the feeling of being watched (if you have the webcam on all the time), but still convey things like whether you're there or not, and maybe even mood?

**Comment by lpmi-13** [comment]
The pure js person detection is probably good enough now to do this sans python, though not sure about smile detection
