### ISSUE TITLE
😀/🤐/🤬 Slack sentiment aggregator

### ISSUE THREAD

**Issue by spikeheap** [remotehack/remotehack.github.io#8]
Could we help organisations keep track of Slack channels and the overall team?

If we ran sentiment analysis over a team to build up a picture of what things normally look like, this could catch spiralling conversations or teams which are getting fed up

**Comment by mikerhyssmith** [comment]
I'm a big fan of this idea !

**Comment by spikeheap** [comment]
Here's what Mike and I hacked on on Saturday: https://github.com/remotehack/remote-sentiment
