### ISSUE TITLE
Link to GitHub

### ISSUE THREAD

**Issue by benfoxall** [remotehack/remotehack.github.io#97]
Should we link from the site to the GitHub repo?

**Comment by lpmi-13** [comment]
We do...dont we?

**Comment by lpmi-13** [comment]
![Uploading Screenshot_20210127-194922_Chrome.jpg…]()

**Comment by lpmi-13** [comment]
![Screenshot_20210127-194922_Chrome](https://user-images.githubusercontent.com/5070516/106045524-f08e6b80-60d8-11eb-96b0-a23bce9b2342.jpg)

**Comment by benfoxall** [comment]
Ah, I forgot about that!

Perhaps we should have it more prominent?  Like maybe in the footer of the page or something?

**Comment by lpmi-13** [comment]
I will pre-approve that PR!
